Austumate/Controllers/CarouselController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Austumate.Models;
using System.IO;
using Microsoft.AspNet.Identity;

namespace Austumate.Controllers
{
    [Authorize]
    public class CarouselController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        
        public async Task<ActionResult> Index()
        {
            var carousels = db.Carousels.Include(c => c.Profile);
            return View(await carousels.ToListAsync());
        }

        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> UserCarousels()
        {
            var carousels = db.Carousels.Include(c => c.Profile);
            return View(await carousels.ToListAsync());
        }

        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarouselModel carouselModel = await db.Carousels.FindAsync(id);
            if (carouselModel == null)
            {
                return HttpNotFound();
            }
            return View(carouselModel);
        }

        public ActionResult Create()
        {
            ViewBag.ProfileID = new SelectList(db.Profiles, "ProfileID", "FirstName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ProfileID,CarouselImage")] CarouselModel carouselModel, HttpPostedFileBase image)
        {
            carouselModel.ProfileID = User.Identity.GetUserId();
            string FileName = Path.GetFileName(image.FileName);
            string ImagePath = Server.MapPath("~/Images/" + FileName);
            image.SaveAs(ImagePath);
            carouselModel.CarouselImage = "~/Images/" + FileName;
            if (ModelState.IsValid)
            {
                db.Carousels.Add(carouselModel);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.ProfileID = new SelectList(db.Profiles, "ProfileID", "FirstName", carouselModel.ProfileID);
            return View(carouselModel);
        }

        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarouselModel carouselModel = await db.Carousels.FindAsync(id);
            if (carouselModel == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProfileID = new SelectList(db.Profiles, "ProfileID", "FirstName", carouselModel.ProfileID);
            return View(carouselModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ProfileID,CarouselImage")] CarouselModel carouselModel, HttpPostedFileBase image)
        {
            carouselModel.ProfileID = User.Identity.GetUserId();
            string FileName = Path.GetFileName(image.FileName);
            string ImagePath = Server.MapPath("~/Images/" + FileName);
            image.SaveAs(ImagePath);
            carouselModel.CarouselImage = "~/Images/" + FileName;
            if (ModelState.IsValid)
            {
                db.Entry(carouselModel).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.ProfileID = new SelectList(db.Profiles, "ProfileID", "FirstName", carouselModel.ProfileID);
            return View(carouselModel);
        }

        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarouselModel carouselModel = await db.Carousels.FindAsync(id);
            if (carouselModel == null)
            {
                return HttpNotFound();
            }
            return View(carouselModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            CarouselModel carouselModel = await db.Carousels.FindAsync(id);
            db.Carousels.Remove(carouselModel);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Austumate/Views/Carousel/Create.cshtml
@model Austumate.Models.CarouselModel

@{
    ViewBag.Title = "Create";
}

<h2 class="mt-5 mb-4">Upload Carousel</h2>


@using (Html.BeginForm("Create", "Carousel", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group" hidden>
            @Html.LabelFor(model => model.ProfileID, "ProfileID", htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                @Html.DropDownList("ProfileID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProfileID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CarouselImage, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                <input type="file" name="image" />
                @Html.ValidationMessageFor(model => model.CarouselImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default nav-link" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Austumate/Views/Carousel/Delete.cshtml
@model Austumate.Models.CarouselModel

@{
    ViewBag.Title = "Delete";
}

<h2 class="mt-5 mb-4">Delete</h2>

<h3 class="mb-3">Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Profile.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Profile.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CarouselImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarouselImage)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default nav-link" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Austumate/Views/Carousel/Details.cshtml
@model Austumate.Models.CarouselModel

@{
    ViewBag.Title = "Details";
}

<h2 class="mt-5 mb-4">Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Profile.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Profile.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CarouselImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarouselImage)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProfileID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Austumate/Views/Carousel/Edit.cshtml
@model Austumate.Models.CarouselModel

@{
    ViewBag.Title = "Edit";
}

<h2 class="mt-5 mb-4">Change Carousel</h2>

@using (Html.BeginForm("Edit", "Carousel", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProfileID)

        <div class="form-group">
            @Html.LabelFor(model => model.CarouselImage, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                <input type="file" name="image" />
                @Html.ValidationMessageFor(model => model.CarouselImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default nav-link" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Austumate/Views/Carousel/Index.cshtml
@using Microsoft.AspNet.Identity
@model IEnumerable<Austumate.Models.CarouselModel>

@{
    ViewBag.Title = "Index";
}

<h2 class="mt-5 mb-4">Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            <p>Name</p>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CarouselImage)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        if (item.ProfileID == User.Identity.GetUserId())
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Profile.FirstName)
                </td>
                <td>
                    <img src="@Url.Content(item.CarouselImage)" height="100" width="100" />
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ProfileID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ProfileID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ProfileID })
                </td>
            </tr>
        }
    }

</table>

Austumate/Views/Carousel/UserCarousels.cshtml
@model IEnumerable<Austumate.Models.CarouselModel>

@{
    ViewBag.Title = "UserCarousels";
}

<h2 class="mt-5 mb-4">User Carousels</h2>

<table class="table">
    <tr>
        <th>
            <p>Name</p>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CarouselImage)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Profile.FirstName)
        </td>
        <td>
            <img src="@Url.Content(item.CarouselImage)" height="100" width="100" />
        </td>
    </tr>
}

</table>